In [11]:
import numpy as np
import pandas as pd
import tqdm
from utils import *

In [12]:
path = "./data/text8.txt"
path2 = "./data/testing.txt"

In [13]:
import pickle

In [14]:
x  = np.array([[12,3],[3,3,2],[1,2,3]])

In [15]:
x1 = x[1:3]

In [16]:
np.array(x1.tolist())

array([[3, 3, 2],
       [1, 2, 3]])

In [17]:
path = "./data/text8.txt"

In [ ]:
word2idx , idx2word, word_freq = corpus_making(path, load= False, batch= 50000)
train_set_idx = train_data_gen(path = path, word2idx = word2idx, max_distance= 3, load = False, batch = 50000, save = False)

100000000


Making Train_set:  89%|█████████████████████████████████████████████████████▍      | 1782/2000 [01:50<00:12, 17.05it/s]

In [10]:
train_set_idx

NameError: name 'train_set_words' is not defined

In [9]:
len(train_set_idx)

16997207

In [12]:
seed = np.random.choice(len(train_set_idx), 10)

In [29]:
import heapq

In [71]:
heapq.heapify(a)

In [109]:
heap[0][3]

[6, 5, [3, 4, [1, 5], [2, 3]], [3, 8]]

In [117]:
_build_binary_tree(heap)

3


array([[0, 0, 0, 2, 1, 0, 3],
       [0, 1, 0, 2, 1, 0, 2],
       [0, 0, 1, 2, 1, 0, 3],
       [1, 0, 0, 2, 0, 0, 1]])

In [8]:
import torch
from torch import nn as nn

In [7]:
a = torch.rand(10, 20)

In [13]:
b = torch.rand(10, 1).to(torch.long)

In [14]:
criterion = nn.CrossEntropyLoss()

In [42]:
np.random.choice(10,1)

array([1])

In [16]:
b

tensor([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0]])

In [17]:
criterion = nn.CrossEntropyLoss()

output = torch.randn(500, 254439).float()
target = torch.FloatTensor(500,1).uniform_(0, 254439).long()
target = target.squeeze(1)
loss = criterion(output, target)

In [18]:
loss

tensor(12.9633)

In [13]:
output.shape

torch.Size([500, 254439])

In [14]:
target.shape

torch.Size([500])

In [33]:
r = np.random.random((10,10))

In [41]:
r[:,np.random.choice(10,1)]

array([[0.8101753 ],
       [0.11895232],
       [0.504396  ],
       [0.10313401],
       [0.0936067 ],
       [0.27333456],
       [0.7104687 ],
       [0.90259739],
       [0.60154531],
       [0.97946196]])

In [6]:
n, m = _Huffman_Tree(word2idx)

Huffman_Tree:  92%|███████████████████████████████████████████████████▋    | 234882/254439 [00:01<00:00, 214685.61it/s]


IndexError: index out of range

In [20]:
emb = nn.Embedding(3,2,padding_idx= 2)

In [22]:
li = [1,2,3]

In [23]:
len(li)

3