In [1]:
import numpy as np
import pandas as pd
import tqdm
from utils import *

In [2]:
path = "./data/text8.txt"
path2 = "./data/testing.txt"

In [3]:
import pickle

In [4]:
x  = np.array([[12,3],[3,3,2],[1,2,3]])

In [5]:
x1 = x[1:3]

In [6]:
np.array(x1.tolist())

array([[3, 3, 2],
       [1, 2, 3]])

In [7]:
path = "./data/text8.txt"

In [9]:
word2idx , idx2word = corpus_making(path, load= False, batch= 50000)
word2idx, idx2word = delete_low_freq(word2idx, idx2word)

MAKING CORPUS: 100%|██████████████████████████████████████████████████████████████| 2000/2000 [00:11<00:00, 181.76it/s]


In [ ]:
train_set_idx = train_data_gen(path = path, word2idx = word2idx, max_distance= 3, load = False, batch = 50000, save = False)

In [12]:
x, max_ = _Huffman_Tree(word2idx)

Huffman_Tree: 100%|██████████████████████████████████████████████████████████| 63662/63662 [00:00<00:00, 290148.10it/s]


In [11]:
from utils import _Huffman_Tree

In [15]:
import torch

In [17]:
a = torch.rand(3,3)

In [19]:
output = torch.sigmoid(a)
target = torch.zeros_like(output)

In [32]:
criterion = torch.nn.BCELwithoss()

AttributeError: module 'torch.nn' has no attribute 'BCELwithoss'

In [30]:
criterion(output,target)

tensor(1.0714)

In [25]:
target

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [28]:
output

tensor([[0.6808, 0.7258, 0.5605],
        [0.7001, 0.6335, 0.6760],
        [0.6952, 0.5700, 0.6385]])

In [31]:
a

tensor([[0.7574, 0.9733, 0.2433],
        [0.8475, 0.5471, 0.7354],
        [0.8247, 0.2820, 0.5687]])

In [34]:
cr2 = torch.nn.BCEWithLogitsLoss()

In [35]:
cr2(a,target)

tensor(1.0714)

In [36]:
criterion(output,target)

tensor(1.0714)

In [42]:
x[0]

[680,
 0,
 [1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
 [63661,
  63660,
  63658,
  63654,
  63645,
  63629,
  63600,
  63549,
  63460,
  63295,
  62987,
  62428,
  61449,
  59854,
  57361]]