In [1]:
import numpy as np
import pandas as pd
import tqdm
from utils import *
from utils import _Huffman_Tree
from model.word2vec import *

In [2]:
path = "./data/text8.txt"
path2 = "./data/testing.txt"

In [3]:
import pickle

In [4]:
x  = np.array([[12,3],[3,3,2],[1,2,3]])

In [5]:
x1 = x[1:3]

In [6]:
np.array(x1.tolist())

array([[3, 3, 2],
       [1, 2, 3]])

In [7]:
path = "./data/text8.txt"

In [8]:
word2idx , idx2word = corpus_making(path, load= False, batch= 50000)
word2idx, idx2word = delete_low_freq(word2idx, idx2word, 10)

MAKING CORPUS: 100%|██████████████████████████████████████████████████████████████| 2000/2000 [00:10<00:00, 184.48it/s]


In [9]:
train_set_idx, total_len = train_data_gen(path = path, word2idx = word2idx, max_distance= 3, load = False, batch = 50000, save = False)

Making Train_set: 100%|████████████████████████████████████████████████████████████| 2000/2000 [00:34<00:00, 57.32it/s]


In [10]:
b_tree, max_ = _Huffman_Tree(word2idx)

Huffman_Tree: 100%|██████████████████████████████████████████████████████████| 47158/47158 [00:00<00:00, 248872.29it/s]


In [128]:
label = np.array([[path, idx_path] for _, _, idx_path ,path in b_tree])

In [150]:
batch_train = train_set_idx[np.random.choice(100, 10)]

x_train = batch_train[:, 3]
label_train_idx = np.delete(batch_train , 3, axis =1)

#N x [path(2C), idx_path(2C)]
label_train = [label[idx] for idx in label_train_idx]

In [160]:
for i , j in label_train[0]:
    print(i)
    print(j)

[47157, 47156, 47153, 47147]
[1, 0, 0, 1]
[47157, 47156, 47153, 47148, 47138, 47120, 47088, 47029, 46926, 46735, 46382, 45749]
[1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1]
[47157, 47156, 47154, 47150, 47142, 47126, 47098, 47049, 46965, 46807, 46515, 45985]
[1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1]
[47157, 47156, 47154, 47149, 47140, 47122, 47092, 47037, 46941, 46762, 46432, 45836, 44810, 43139, 40571]
[1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0]
[47157, 47156, 47153, 47148, 47137, 47118, 47084, 47021, 46913, 46709, 46334, 45664, 44521]
[1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1]
[47157, 47155, 47152, 47146, 47134, 47112, 47075, 47005, 46883, 46652, 46227]
[0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0]


In [120]:
model = skip_gram_with_Hierarchy(vocab_size = len(word2idx), projection_layer = 300, sample_size = 5)
optimizer = torch.optim.SGD(model.parameters(), lr = 0.025)
#criterion = nn.CrossEntropyLoss()
criterion = torch.nn.BCELoss()

In [163]:
batch_train = train_set_idx[np.random.choice(1000, 10)]

In [164]:
loss = 0
for out, lab in zip(a,b):
    #print(out,lab)
    lab = lab.to(torch.float)
    loss = loss + criterion(out,lab)
    

TypeError: 'int' object is not callable

In [168]:
a = torch.rand(1,10)
b = torch.zeros(10)

In [169]:
criterion(a,b)

C:\Users\dilab\Anaconda3\lib\site-packages\torch\nn\modules\loss.py:498: UserWarning: Using a target size (torch.Size([10])) that is different to the input size (torch.Size([1, 10])) is deprecated. Please ensure they have the same size.
  return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)


tensor(0.8702)

In [170]:
b

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [171]:
a

tensor([[0.5173, 0.3482, 0.1775, 0.5239, 0.3554, 0.0577, 0.8526, 0.2279, 0.9596,
         0.5161]])

In [172]:
a

tensor([[0.5173, 0.3482, 0.1775, 0.5239, 0.3554, 0.0577, 0.8526, 0.2279, 0.9596,
         0.5161]])

In [173]:
a = np.random.random((10,10))

In [175]:
a[1,2,3,4]

IndexError: too many indices for array