In [1]:
import numpy as np
from model.layers import Embedding, Sigmoid, Softmax, Linear
from model.w2v_np import HS_skipgram, BCELossWithSigmoid
from preprocess import *
from optim.optimizer import SGD
from itertools import repeat
import time
import pickle

In [6]:
import os 
from collections import Counter
from fuel.utils import find_in_data_path
from tqdm import tqdm

In [4]:
collect = Counter()
batch = 9

In [2]:
batch_size = 300
sample_size = 5
path = "./data/text8.txt"

path = "./1-billion-word/training-monolingual.tokenized.shuffled"

with open("./data.pickle", 'rb') as f:
    save = pickle.load(f)

word2idx = save["word2idx"]
idx2word = save["idx2word"]
count = save["count"]
file_path = save["file_path"]

node, max_depth = Huffman_Tree(count)


def batch_words(paths):
    words = []
    for path in paths:
        word = recall_word(path)
        words += word

    return words

#sample_size random하게 바꿈. --> 한 corpus에서 더 다양하게 보는게 가능!
model = HS_skipgram(len(word2idx), 300, lr = 0.0025)
criterion = BCELossWithSigmoid()
optimizer = SGD(lr = 0.0025)

Padding Paths: 100%|███████████████████████████████████████████████████████| 500001/500001 [00:00<00:00, 536188.82it/s]


In [10]:
def evaluate(path, model, word2idx, idx2word):
    with open("./best22model.pickle", 'rb') as f:
        x = pickle.load(f)


    model.params = x
    for i in range(20,30):
        #ex = np.random.choice(len(word2idx), 1)[0]
        model.query(idx2word[i], word2idx, idx2word, top = 10)




evaluate("",model,word2idx, idx2word)

at
Edinburgh 0.30282414
Park 0.31162
Saturday 0.31169322
Road 0.32504782
evening 0.3295605
London 0.33690256
outside 0.33829042
attended 0.34984368
near 0.38105133
At 0.6532879
it
simply 0.45117143
everything 0.45989132
that 0.46542183
anything 0.47166863
quite 0.4724815
everyone 0.4885736
It 0.49071217
really 0.50171274
something 0.50485367
he 0.51202184
by
triggered 0.2541145
driven 0.25763038
supported 0.2597864
from 0.26166037
being 0.26614624
funded 0.26727533
largely 0.27941975
whose 0.27976212
among 0.28588504
widely 0.2900728
from
onto 0.28734103
while 0.29075235
inside 0.29157045
received 0.29191315
within 0.30176643
around 0.30792987
into 0.3343986
across 0.33947584
sent 0.3431851
through 0.40406415
be
receive 0.38566965
easily 0.38764942
apply 0.38818425
begin 0.39031178
have 0.39374387
mean 0.39423874
probably 0.4324797
happen 0.4447912
prove 0.45811146
remain 0.48717964
have
already 0.3671231
believe 0.37119406
some 0.3796713
never 0.38885027
be 0.39374387
having 0.4074527

In [13]:
node[-10]

array([0.00000e+00, 1.00000e+00, 1.00000e+00, 0.00000e+00, 1.00000e+00,
       1.00000e+00, 0.00000e+00, 1.00000e+00, 0.00000e+00, 1.00000e+00,
       0.00000e+00, 1.00000e+00, 1.00000e+00, 0.00000e+00, 1.00000e+00,
       0.00000e+00, 1.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 1.00000e+00, 0.00000e+00, 4.99999e+05, 4.99997e+05,
       4.99994e+05, 4.99988e+05, 4.99975e+05, 4.99953e+05, 4.99914e+05,
       4.99841e+05, 4.99711e+05, 4.99472e+05, 4.99040e+05, 4.98261e+05,
       4.96965e+05, 4.94911e+05, 4.91768e+05, 4.87105e+05, 4.80318e+05,
       4.70563e+05, 4.56678e+05, 4.37234e+05, 4.10310e+05, 3.73623e+05,
       3.24302e+05, 2.59071e+05, 1.77603e+05, 8.50080e+04, 4.99500e+03,
       0.00000e+00, 2.70000e+01])

In [11]:
word2idx["Paris"]

1661

In [12]:
word2idx["Korea"]

930

In [27]:
with open("./best22model.pickle", 'rb') as f:
    x = pickle.load(f)


model.params = x

In [28]:
W_in = model.params[0]

In [29]:
a = W_in[word2idx["quick"]]
b = W_in[word2idx["quickly"]]
c = W_in[word2idx["slow"]]

In [30]:
r = cosine_similarity(W_in, c+b-a)

In [31]:
result = r.argsort()[-15:-1]

In [32]:
result

array([ 703, 3930, 1638, 2322,  829, 2026, 1156,  593, 1994,  308, 1684,
       3834,  941, 1003], dtype=int64)

In [33]:
for i in result:
    print(idx2word[i])

fall
temperatures
falling
weak
soon
fast
rising
continue
grow
economy
inflation
slowly
recession
quickly


In [17]:
tt = np.random.random((1000000))
aa = np.random.random((1000000))
st = time.time()
for i in zip(tt,aa):
    z = i
    
print(time.time() - st)

0.13965392112731934


In [18]:
st = time.time()
for i in tt:
    z = i
print(time.time() - st)

0.09175300598144531


In [29]:
q = [1,2,3,4,1,2,3,4,1,2]
r = [1,2,6,3,2]

In [45]:
a = []
for i in range(100000):
    a.append(q)
    a.append(r)

In [53]:
max_depth

28

In [15]:
test = np.zeros((10,10))

In [27]:
len(a)

2000

In [90]:
st = time.time()
for i in a:
    z = i
print(time.time() - st)

0.009998321533203125


In [91]:
st = time.time()
for i in range(200000):
    z = i
print(time.time() - st)

0.01296377182006836


In [75]:
st = time.time()
for i in range(10000):
    np.random.choice(100000000,500)
print(time.time() - st)

0.13361883163452148


In [ ]:
for i in range(10000):
    

In [76]:
import random

In [85]:
random.random() * 1e+9

534123436.1543744

In [93]:
np.random.permutation(1000000)

array([515059,  13757, 113888, ..., 315601, 832453, 176939])